-keepclassmembernames class com.mikepenz.community_material_typeface_library.CommunityMaterial$Icon { *; }
-keepclassmembernames class com.mikepenz.community_material_typeface_library.CommunityMaterial$Icon2 { *; }
